export const strings = {
  appTitle: "WhatsApp",
  archived: "Archivados",
  archivedCount: "0",
  searchPlaceholder: "Preguntar a Meta AI o buscar",
  tabs: {
    all: "Todos",
    unread: "No leídos",
    favorites: "Favoritos",
    groups: "Grupos",
  },
  emptyChats: "No hay chats aún. Crea uno nuevo con el botón “+”.",
  lockedPreview: "Chat protegido",
  lock: {
    sectionTitle: "Bloqueo con clave",
    protected: "Este chat está protegido con una clave.",
    setLabel: "Clave (deja vacío para no bloquear)",
    changeLabel: "Nueva clave (deja vacío para mantener)",
    placeholder: "Clave o PIN",
    remove: "Quitar bloqueo",
    warning: "⚠️ No hay recuperación de clave. Es todo local (sin usuarios, mail ni backend): si la olvidás, perdés el acceso a este chat.",
    unlockTitle: "Chat protegido",
    unlockPrompt: "Ingresá la clave para abrir este chat.",
    unlockError: "Clave incorrecta.",
    unlock: "Abrir",
  },
  emptyMessages: "No hay mensajes. Escribe para comenzar la conversación.",
  composer: {
    placeholder: "Mensaje",
    editPlaceholder: "Editar mensaje…",
    attach: "Adjuntar archivo",
    camera: "Abrir cámara",
    send: "Enviar",
    save: "Guardar edición",
  },
  chatMenu: {
    contactInfo: "Info del contacto",
    archive: "Archivar chat",
    unarchive: "Desarchivar chat",
    pin: "Fijar chat",
    unpin: "Desfijar chat",
    clear: "Vaciar chat",
    showOnline: "Mostrar \"en línea\"",
    hideOnline: "Ocultar \"en línea\"",
    online: "en línea",
    delete: "Eliminar chat",
    toggleComposeMe: {
      send: "Enviar mensaje",
      receive: "Recibir mensaje",
    },
    addTo: "Añadir a",
    removeCategory: "Quitar categoría",
    editMessage: "Editar mensaje",
    deleteMessage: "Borrar mensaje",
    search: "Buscar",
    searchPlaceholder: "Buscar en el chat",
    searchNoResults: "Sin resultados",
    closeSearch: "Cerrar búsqueda",
  },
  mainMenu: {
    broadcast: "Nueva difusión",
    linked: "Dispositivos vinculados",
    settings: "Configuración",
    toggleThemeLight: "Cambiar a modo claro",
    toggleThemeDark: "Cambiar a modo oscuro",
    exportNotes: "Exportar notas",
    importNotes: "Importar notas",
    about: "Acerca de",
  },
  settings: {
    title: "Configuración",
    appNameLabel: "Nombre de la app",
    appNamePlaceholder: "Ej: WhatsApp, Notas…",
    appNameHint: "Se muestra como título en la pantalla principal.",
    platformLabel: "Estilo de interfaz",
    platformHint: "Cambia el aspecto entre Android e iOS (header, barra inferior, botón de nuevo chat).",
    back: "Volver",
  },
  about: {
    title: "WhatsApp Notes",
    description: "Bloc de notas con interfaz estilo WhatsApp. Cada chat es un anotador. Todo se guarda localmente en tu dispositivo.",
    versionLabel: "Versión",
    close: "Cerrar",
  },
  importConfirm: "Importar reemplazará todos tus chats y categorías actuales. ¿Continuar?",
  importError: "El archivo no es un export válido de WhatsApp Notes.",
}

export const APP_VERSION = "1.2.0"
